[project]
name = "road-trip"
version = "1.1"
description = "Road Trip Planner"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "dataframe-with-buttons>=1.0.0",
    "folium~=0.19",
    "opencage~=3.1",
    "pandas~=2.2",
    "polyline~=2.0",
    "pygithub~=2.6",
    "requests~=2.32",
    "streamlit~=1.44",
    "streamlit-folium~=0.24",
]
